### ISSUE TITLE
Pymef failed while reading

### ISSUE THREAD

**Issue by nelagri** [msel-source/pymef#17]
Hi Jan,

I have encounter another problem. I created a signal which consists on the sum of two sine waves. When I try to read this signal, Pymef fails with exit code -1073740940 (0xC0000374). 

For the record, frequencies of these sine waves is 100 and 150 Hz (sampling frequency is 1 kHz). Sine waves of frequencies 101 and 150 Hz are correctly read. 

Corresponding MEF file is attached.

Thank you for your reply.
Nela

[test_mef_writing_fail.mefd.zip](https://github.com/msel-source/pymef/files/3928545/test_mef_writing_fail.mefd.zip)

**Comment by freemanix** [comment]
I've located the source of the problem. The difference buffer allocated in read_mef_ts_data() is 1 byte shorter than it has to be. This is because meflib RED_decode() starts with additional -128 byte inserted in the diffference buffer, thus last write is out of the allocated memory. This corrupts heap and causes the crash.

I've included this minimal patch:
[fix-allocation.patch.txt](https://github.com/msel-source/pymef/files/3931894/fix-allocation.patch.txt)

**Comment by cimbi** [comment]
Thanks @freemanix. I'll try to fix it this weekend

**Comment by cimbi** [comment]
@nelagri is there a password for the session?

**Comment by cimbi** [comment]
Fixed by 3c0be08a
